### ISSUE TITLE
[Feature] Clojure - Multi-arity functions

### ISSUE THREAD

**Issue by grierson** [p00f/alabaster_dark.nvim#3]
Multi-arity functions in Clojure are not highlighted

<img width="306" alt="Screenshot 2022-07-21 at 08 44 31" src="https://user-images.githubusercontent.com/1732552/180158534-f2b5a804-5a01-425a-87da-0c8f4ed1f736.png">

**Comment by p00f** [comment]
Thanks, this is fixed now
