### ISSUE TITLE
Do you know of a light version of alabaster for nvim?

### ISSUE THREAD

**Issue by martisj** [p00f/alabaster_dark.nvim#4]

**Comment by martisj** [comment]
Is it this one? https://github.com/agudulin/vim-colors-alabaster

**Comment by p00f** [comment]
Ye

**Comment by p00f** [comment]
@martisj https://todo.sr.ht/~p00f/alabaster_dark.nvim/1

**Comment by p00f** [comment]
@martisj I've started working on a light version, can you try out the `light` branch and report wrong highlights? You need to `set background=light` before setting the colorscheme, and the colorscheme is now just `alabaster`

So instead of
```vim
colorscheme alabaster_dark
```
you do
```vim
set background=light
colorscheme alabaster
```

**Comment by p00f** [comment]
I've merged the light branch

**Comment by martisj** [comment]
Legendary @p00f 🙏 Thank you so much! it works a lot better than the other light alabaster.
